name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: crispyduck
  #         password: ${{ secrets.DOCKER_TOKEN }}
  #     - name: Build and push
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         tags: |
  #           crispyduck/chad-gupity:latest
  #           crispyduck/chad-gupity:${{ github.sha }}

  deploy:
    # needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: azure/setup-kubectl@v3
      with:
        version: v1.22.13
    - name: Write to file
      run: mkdir -p ~/.kube && echo $KUBECONFIG | base64 --decode > ~/.kube/config
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
    - name: get kubectl version
      run: kubectl version
    - name: get deployment
      run: kubectl get deployment chad-gupity